- 中国前沿计算机体系结构
- 第一讲基本常识概念
- 并行计算机
  - 网络性能指标
  - 一维
  - 二维
  - 超立方
  - 静态互连网络表 理解
- 动态互连对比，优缺点介绍，复杂度和带宽性能
- 弗林分类
- 数据流
- SIMD同类的对比
- 内存访问模型
- 共享内存和分布式内存（重要！）
- smp/mpp/机群比较表
- cpu,gpu,ai芯片对比 简答题
- 第四章模型大概意思 对比 简答题 
- logp模型图
- 不同约束条件的加速比 图对应哪种加速比 给定理对应哪一种
- 等效率
  - 等效率测度如何计算
- 并行算法的一般设计过程各个概念
- 矩阵乘法
- DNS矩阵乘法结论 处理器数目n的三次方，运行时间ologn
- 编程题aprenp 实验自己做
- MPI编程题 实验自己做
- collective communication 通信完数据什么样子
- example of word count job mapreduce 
  - map reduce概念
  - execute mapreduce：redundantexecution等三个图
- 云计算ppt概念
- 什么是虚拟机 基本概念 虚拟化分类
- 云计算的服务模式