- K8S的pod之间是如何通信的
  - Kubernetes（K8S）中 Pod 与 Pod 之间的通信，本质上依赖 扁平网络模型 + 虚拟网络层 + kube-proxy 服务发现机制，无需手动做端口映射，任何 Pod 都能直接访问其他 Pod 的 IP（只要网络策略允许）。
  - 核心原则：Pod IP 全局唯一、可直接通信
  - Pod 跨节点通信如何实现？
    - Pod 间通信靠 CNI 网络插件
      - 它们负责
        - 给每个 Pod 分配 IP
        - 创建虚拟网卡（veth pair）
        - 维护节点路由表
        - 让不同 Node 之间 Pod 能通信

