- git想切换分支然后不想提交代码怎么解决   
  - git stash
    - 把改动临时存起来，切换完分支后再取出来。
    - 假设现在在dev修改代码
    - 这时你修改了几个文件，但还没提交
    - 然后你想切到 main 分支看点别的东西。但是 Git 不让切，因为你有未提交的修改
    - git stash会将代码区的修改保存到一个栈中，并恢复工作区到上次pull的状态
    - git stash pop
      - 切换回 dev 分支后，把之前存的改动取出来并删除stash记录
    - git stash apply
      - 切换回 dev 分支后，把之前存的改动取出来但不删除stash记录
  - 临时提交到本地但不推送
  - 如果想保留但在多个分支都可用 git switch other-branch --merge
    - 提是：改动的文件与目标分支没有冲突，否则 Git 会拒绝切换。
