= 牛客面经
- treeMap和hashMap的区别和底层实现
  - 是否顺序存储：
    - treeMap按key顺序存储
    - hashMap不按顺序存储
  - key可以为null吗？ value呢？
    - treeMap的key不能为null，因为需要排序
    - hashMap可以为null,但是只有一个，因为有覆盖问题
    - value都可以为null，且多个
  - 线程安全
    - 都不是线程安全的
  - 插入，删除时间复杂度
    - treeMap是logn,因为基于红黑树
    - hashMap平均O（1），最坏为O（n），碰撞严重退化成链表，但是链表长度大于8会变成红黑树（jdk1.8以后）
  - 底层实现
    - treeMap的底层实现是红黑树
    - hashMap的底层实现是数组+链表或红黑树 
- ==和equals的区别
  - 基本类型不能使用equals
  - ==基本类型比值，引用类型比地址
  - equals默认比地址，重写后不一定
  - String、Integer、Date、集合类中的元素，都重写了 equals()，用来比较内容。所以==和equals可能不一样
- java中BIO,NIO，AIO区别，如何实现，是否有过实际的使用
  - BIO（blocking IO）：就是传统的 java.io 包，它是基于流模型实现的，交互的方式是同步、阻塞方式，也就是说在读入输入流或者输出流时，在读写动作完成之前，线程会一直阻塞在那里，它们之间的调用是可靠的线性顺序。优点是代码比较简单、直观；缺点是 IO 的效率和扩展性很低，容易成为应用性能瓶颈。
  - NIO（non-blocking IO） ：Java 1.4 引入的 java.nio 包，提供了 Channel、Selector、Buffer 等新的抽象，可以构建多路复用的、同步非阻塞 IO 程序，同时提供了更接近操作系统底层高性能的数据操作方式。
  - AIO（Asynchronous IO） ：是 Java 1.7 之后引入的包，是 NIO 的升级版本，提供了异步非堵塞的 IO 操作方式，所以人们叫它 AIO（Asynchronous IO），异步 IO 是基于事件和回调机制实现的，也就是应用操作之后会直接返回，不会堵塞在那里，当后台处理完成，操作系统会通知相应的线程进行后续的操作。
  - 底层实现区别
    - BIO：一个请求一个线程，线程调用 socket.read() 时挂起，直到有数据。
    - NIO：基于 I/O 多路复用（select/poll/epoll），一个线程能同时处理多个连接。
    - AIO：基于 操作系统异步 I/O 能力（如 Linux 的 io_uring、Windows 的 IOCP）。
  #image("Screenshot_20250907_235916.png")
  #image("Screenshot_20250908_000213.png")
- 为什么很多大厂只用post发请求
  - URL长度限制
    - GET 请求参数写在 URL 上，不同浏览器、代理、服务器对 URL 长度有限制（常见 2KB ~ 8KB）。
    - 在大厂业务场景中，请求参数可能很复杂（JSON、大量条件、批量 ID、加密串），GET 根本放不下。
    - POST 请求参数放在请求体中，长度没有限制。
  - 安全性
    - GET 请求参数暴露在 URL 上，容易出现在
      - 浏览器地址栏
      - 代理/网关日志
      - 浏览器历史记录
    - 敏感数据（如 token、手机号、订单号）用 POST 放在 body 里更安全。
  - 缓存与幂等性问题
    - HTTP 语义里：
      - GET 应该是安全、幂等的 → 浏览器、中间代理可能会缓存
      - POST 不幂等，默认不缓存
    - 在复杂的分布式系统里，大厂不想依赖中间层“自动缓存”的行为，所以干脆都用 POST，自己做缓存控制。
  - 统一网关与监控
    - 大厂通常有 API 网关、统一鉴权、监控系统。
    - 如果方法不统一（有的用 GET，有的用 DELETE），会增加接入和维护的复杂度。
    - 全部用 POST，统一在 header/body 做参数校验、签名验证、加解密，更加简单。
  - 跨域与复杂请求
    - 浏览器里，GET、POST 的简单请求比较好处理。
    - 但如果需要传自定义 header（如 token、签名），很多情况都会变成 复杂请求 (CORS Preflight)。
    - 大厂干脆约定一律 POST，减少前后端沟通成本。
  - 是一种务实选择，而不是规范选择。
