- ARMS系统监控
  - 阿里云
  - 探针技术 javaagent 在java应用启动时或运行时动态修改字节码 无侵入式监控
  - prometheus+Grafana
    - prometheus
      - 时序数据库 拉取模式 
      - 指标类型
      - 内存 预写日志 持久化到硬盘
    - Grafana
      - 数据可视化
- mongodb
  - 文件和集合
  - BSON
  - 数据页，页号，层级
  - 写时复制，b+树
  - cache
  - 写前日志，顺序写入（磁盘随机写入）
  - checkpoint
  - wiredtiger存储引擎
  - server层
    - 解析器
    - 优化器
    - 执行器
  - 路由mongos。，分片
  - 副本集，类似于主从
  - 和mysql对比
  #image("Screenshot_20250823_101851.png")
  #image("Screenshot_20250823_101923.png")
  #image("Screenshot_20250823_101931.png")
- DSTransactional注解
  - 多数据源分布式事务
  - 应用于一个方法同时操作两个库
  - 如果是 跨服务的分布式事务，则需要引入 Seata、RocketMQ 事务消息 等方案，DSTransactional 只适合 单应用多数据源 的场景。
- xxl-job
    - springboot的定时注解在多节点部署时会重复执行，如定时积分增加，多节点就会增加两次
    - 使用xxl-job可以解决这个问题
  - 分布式平台的作用
    - 分布式调度平台可以保证高可用
    - 防止重复执行
    - 突破单机处理极限
  - #image("Screenshot_20250915_224617.png")
  - 执行器
    - 配置时需要配置job类和config类
    - 要执行job类的代码，需要到调度中心去手动执行
      - 配置新增任务
      - 选择执行器执行
    - bean模式
      - job类实现加入xxljob注解，调度中心指定名称，会找到执行器中同名方法调用
    - glue模式
      - GlueIDE编辑代码指定我们要调用执行器中的哪个方法
    - 需要注意多机部署下的执行器端口号要不同
    - 多机部署可选择负载均衡策略
    - 分片广播
      - 会给执行器传递分配总数和分配索引
      - 如果有2000条记录，可以根据id取模分片总数得到的序号和分配索引进行匹配
      - 如果分配总数是2,索引是0，那么id%2=0的记录就会被这个执行器处理。
      - 这样就能提高效率，并且效率随着分片总数增加而增加
      #image("Screenshot_20250915_231454.png")
      #image("Screenshot_20250915_231507.png")
- minio
  - 适合公司或个人想要自建私有云存储，自己管数据。
  - 自建的对象存储服务
  #image("Screenshot_20250915_232223.png")
- Sa-token
- snailjob
